project:
  type: website
  output-dir: docs
  
website:
  title: "r9website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: greatlakes.qmd
        text: Great Lakes
      - href: eastern.qmd
        text: Eastern
      - href: centralplains.qmd
        text: Central Plains 
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

